### ISSUE TITLE
test sonucu çıktı cümlesi ile teste giren cümle aynı

### ISSUE THREAD

**Issue by sukruburakcetin** [StarlangSoftware/TurkishSpellChecker-Py#3]
> from Corpus.Sentence import Sentence
from NGram.NGram import NGram
from NGram.NoSmoothing import NoSmoothing
from MorphologicalAnalysis.FsmMorphologicalAnalyzer import FsmMorphologicalAnalyzer

>from SpellChecker.NGramSpellChecker import NGramSpellChecker

>fsm = FsmMorphologicalAnalyzer("../turkish_dictionary.txt", "../turkish_misspellings.txt",
                               "../turkish_finite_state_machine.xml")
>nGram = NGram("../ngram.txt")
>nGram.calculateNGramProbabilitiesSimple(NoSmoothing())

>nGramSpellChecker = NGramSpellChecker(fsm, nGram, False)
>sentence = Sentence("dışişleri mütseşarı Öymen'in 1997'nin iljk aylğrında Bağdat'a gitmesi öngörülüyor")
>corrected = nGramSpellChecker.spellCheck(sentence)
>print(corrected)

```
D:\Anaconda3\envs\deep-learning-conda-3.7\python.exe C:/Users/BURAK/Desktop/TurkishSpellChecker-Py/test/test-simple.py
dışişleri mütseşarı Öymen'in 1997'nin iljk aylğrında Bağdat'a gitmesi öngörülüyor

Process finished with exit code 0
```

NGramSpellChecker kullanarak bu şekilde bir cümle ile test etmek istediğimde, çıktı olarak, yine aynı sonucu alıyorum. Bu konuda yardımcı olabilir misiniz?

Platform: Windows 10
Python: Anaconda 3.7

**Comment by olcaytaner** [comment]
nGramSpellChecker = NGramSpellChecker(fsm, nGram, False)

satırında üçüncü parametresini True olarak verdiğinizde çalışıyor.

**Comment by muhammedcanpirincci-sudo** [comment]
Çalışmıyor kardeşim.
